apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-role
rules:
- apiGroups:
  - settings.servicecatalog.k8s.io
  resources:
  - podpresets
  verbs:
  - get
  - list
  - watch
